import React, { useState } from 'react';
import { 
  Card, 
  Form, 
  Input, 
  Select, 
  Button, 
  Typography, 
  Space, 
  Row, 
  Col, 
  Tag, 
  message,
  Divider,
  List,
  Popconfirm
} from 'antd';
import { 
  PlusOutlined, 
  DeleteOutlined, 
  SaveOutlined,
  FileTextOutlined,
  TranslationOutlined
} from '@ant-design/icons';
import { motion } from 'framer-motion';
import { useSentenceStore, Sentence, SentenceTranslation, FocusedWord } from '../stores/sentenceStore';
import { useAuthStore } from '../stores/authStore';

const { Title, Text } = Typography;
const { TextArea } = Input;
const { Option } = Select;

const languages = [
  { code: 'zh-CN', name: '中文（简体）' },
  { code: 'zh-TW', name: '中文（繁体）' },
  { code: 'en-US', name: 'English (US)' },
  { code: 'en-GB', name: 'English (UK)' },
  { code: 'ja-JP', name: '日本語' },
  { code: 'ko-KR', name: '한국어' },
  { code: 'fr-FR', name: 'Français' },
  { code: 'de-DE', name: 'Deutsch' },
  { code: 'es-ES', name: 'Español' },
  { code: 'it-IT', name: 'Italiano' },
  { code: 'pt-PT', name: 'Português' },
  { code: 'ru-RU', name: 'Русский' }
];

const SentenceImportPage: React.FC = () => {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState(false);
  const [focusedWords, setFocusedWords] = useState<FocusedWord[]>([]);
  const [translations, setTranslations] = useState<SentenceTranslation[]>([]);
  const [selectedText, setSelectedText] = useState('');

  const { addSentence, sentences } = useSentenceStore();
  const { user } = useAuthStore();

  const getLanguageName = (code: string) => {
    return languages.find(lang => lang.code === code)?.name || code;
  };

  const handleTextSelection = () => {
    const selection = window.getSelection();
    if (selection && selection.toString().trim()) {
      setSelectedText(selection.toString().trim());
    }
  };

  const addFocusedWord = () => {
    if (!selectedText) {
      message.warning('请先选择要聚焦的单词或短语');
      return;
    }

    const newWord: FocusedWord = {
      id: Date.now().toString(),
      wordText: selectedText,
      startPosition: 0, // 简化处理
      endPosition: selectedText.length,
      pronunciation: ''
    };

    setFocusedWords(prev => [...prev, newWord]);
    setSelectedText('');
    message.success('已添加聚焦单词');
  };

  const removeFocusedWord = (id: string) => {
    setFocusedWords(prev => prev.filter(word => word.id !== id));
  };

  const addTranslation = () => {
    const newTranslation: SentenceTranslation = {
      id: Date.now().toString(),
      targetLanguage: '',
      translatedText: '',
      translationType: 'native',
      isAutoGenerated: false
    };
    setTranslations(prev => [...prev, newTranslation]);
  };

  const updateTranslation = (id: string, field: keyof SentenceTranslation, value: any) => {
    setTranslations(prev => prev.map(translation =>
      translation.id === id ? { ...translation, [field]: value } : translation
    ));
  };

  const removeTranslation = (id: string) => {
    setTranslations(prev => prev.filter(translation => translation.id !== id));
  };

  const onFinish = async (values: any) => {
    setLoading(true);
    try {
      const sentenceData: Omit<Sentence, 'id' | 'createdAt' | 'updatedAt'> = {
        originalText: values.originalText,
        languageCode: values.languageCode,
        sourceType: values.sourceType || 'manual',
        sourceReference: values.sourceReference,
        translations: translations.filter(t => t.targetLanguage && t.translatedText),
        focusedWords: focusedWords,
        wordPhrases: [] // 简化处理，暂时为空
      };

      addSentence(sentenceData);
      
      // 重置表单
      form.resetFields();
      setFocusedWords([]);
      setTranslations([]);
      setSelectedText('');
      
      message.success('句子导入成功！');
    } catch (error) {
      message.error('导入失败，请重试');
    } finally {
      setLoading(false);
    }
  };

  const recentSentences = sentences.slice(-5).reverse();

  return (
    <div className="fade-in">
      <div className="page-title">
        <Space>
          <PlusOutlined />
          导入句子
        </Space>
      </div>

      <Row gutter={24}>
        <Col span={16}>
          <Card title="添加新句子" className="learning-card">
            <Form
              form={form}
              onFinish={onFinish}
              layout="vertical"
            >
              <Row gutter={16}>
                <Col span={12}>
                  <Form.Item
                    name="languageCode"
                    label="原句语言"
                    rules={[{ required: true, message: '请选择语言!' }]}
                  >
                    <Select placeholder="选择语言">
                      {languages.map(lang => (
                        <Option key={lang.code} value={lang.code}>
                          {lang.name}
                        </Option>
                      ))}
                    </Select>
                  </Form.Item>
                </Col>
                <Col span={12}>
                  <Form.Item
                    name="sourceType"
                    label="来源类型"
                    initialValue="manual"
                  >
                    <Select>
                      <Option value="manual">手动输入</Option>
                      <Option value="book">书籍</Option>
                      <Option value="clipboard">剪贴板</Option>
                      <Option value="import">导入</Option>
                    </Select>
                  </Form.Item>
                </Col>
              </Row>

              <Form.Item
                name="originalText"
                label="原句内容"
                rules={[{ required: true, message: '请输入原句!' }]}
              >
                <TextArea
                  rows={4}
                  placeholder="请输入原句内容..."
                  onMouseUp={handleTextSelection}
                  onKeyUp={handleTextSelection}
                />
              </Form.Item>

              <Form.Item
                name="sourceReference"
                label="来源引用（可选）"
              >
                <Input placeholder="如：书名、页码等" />
              </Form.Item>

              {/* 聚焦单词 */}
              <div style={{ marginBottom: '24px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                  <Text strong>聚焦单词</Text>
                  <Button
                    type="dashed"
                    size="small"
                    onClick={addFocusedWord}
                    disabled={!selectedText}
                  >
                    添加选中文本
                  </Button>
                </div>
                
                {focusedWords.length > 0 && (
                  <div style={{ marginBottom: '12px' }}>
                    {focusedWords.map(word => (
                      <Tag
                        key={word.id}
                        closable
                        onClose={() => removeFocusedWord(word.id)}
                        style={{ marginBottom: '8px' }}
                      >
                        {word.wordText}
                        {word.pronunciation && ` (${word.pronunciation})`}
                      </Tag>
                    ))}
                  </div>
                )}

                {selectedText && (
                  <Text type="secondary">
                    已选中: "{selectedText}"
                  </Text>
                )}
              </div>

              {/* 翻译 */}
              <div style={{ marginBottom: '24px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                  <Text strong>翻译</Text>
                  <Button
                    type="dashed"
                    size="small"
                    icon={<PlusOutlined />}
                    onClick={addTranslation}
                  >
                    添加翻译
                  </Button>
                </div>

                {translations.map(translation => (
                  <Card
                    key={translation.id}
                    size="small"
                    style={{ marginBottom: '12px' }}
                    actions={[
                      <Popconfirm
                        title="确定删除这个翻译吗？"
                        onConfirm={() => removeTranslation(translation.id)}
                        okText="确定"
                        cancelText="取消"
                      >
                        <DeleteOutlined />
                      </Popconfirm>
                    ]}
                  >
                    <Row gutter={12}>
                      <Col span={8}>
                        <Select
                          placeholder="目标语言"
                          value={translation.targetLanguage}
                          onChange={(value) => updateTranslation(translation.id, 'targetLanguage', value)}
                          style={{ width: '100%' }}
                        >
                          {languages.map(lang => (
                            <Option key={lang.code} value={lang.code}>
                              {lang.name}
                            </Option>
                          ))}
                        </Select>
                      </Col>
                      <Col span={16}>
                        <Input
                          placeholder="翻译内容"
                          value={translation.translatedText}
                          onChange={(e) => updateTranslation(translation.id, 'translatedText', e.target.value)}
                        />
                      </Col>
                    </Row>
                  </Card>
                ))}
              </div>

              <Form.Item>
                <Button
                  type="primary"
                  htmlType="submit"
                  loading={loading}
                  icon={<SaveOutlined />}
                  size="large"
                  block
                >
                  保存句子
                </Button>
              </Form.Item>
            </Form>
          </Card>
        </Col>

        <Col span={8}>
          <Card title="最近导入" className="learning-card">
            {recentSentences.length > 0 ? (
              <List
                dataSource={recentSentences}
                renderItem={(sentence) => (
                  <List.Item>
                    <div style={{ width: '100%' }}>
                      <div style={{ marginBottom: '8px' }}>
                        <Tag color="blue">{getLanguageName(sentence.languageCode)}</Tag>
                        <Text type="secondary" style={{ fontSize: '12px' }}>
                          {sentence.createdAt.toLocaleDateString()}
                        </Text>
                      </div>
                      <Typography.Paragraph ellipsis={{ rows: 2 }} style={{ marginBottom: 0 }}>
                        {sentence.originalText}
                      </Typography.Paragraph>
                      {sentence.focusedWords.length > 0 && (
                        <div style={{ marginTop: '8px' }}>
                          {sentence.focusedWords.map((word, index) => (
                            <Tag key={index}>
                              {word.wordText}
                            </Tag>
                          ))}
                        </div>
                      )}
                    </div>
                  </List.Item>
                )}
              />
            ) : (
              <div className="empty-state">
                <FileTextOutlined className="empty-state-icon" />
                <Text type="secondary">暂无导入记录</Text>
              </div>
            )}
          </Card>
        </Col>
      </Row>
    </div>
  );
};

export default SentenceImportPage;
