// 示例数据 - 用于演示和测试

import { Sentence, SentenceTranslation, FocusedWord } from '../stores/sentenceStore';
import { Book, BookChapter, BookSummary, ReadingNote } from '../stores/bookStore';

// 示例句子数据
export const sampleSentences: Omit<Sentence, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    originalText: "Hello, how are you today?",
    languageCode: "en-US",
    sourceType: "manual",
    sourceReference: "日常对话",
    translations: [
      {
        id: "1",
        targetLanguage: "zh-CN",
        translatedText: "你好，你今天怎么样？",
        translationType: "native",
        isAutoGenerated: false
      }
    ],
    focusedWords: [
      {
        id: "1",
        wordText: "Hello",
        startPosition: 0,
        endPosition: 5,
        pronunciation: ""
      }
    ],
    wordPhrases: []
  },
  {
    originalText: "今日（きょう）は天気（てんき）がいいですね。",
    languageCode: "ja-JP",
    sourceType: "manual",
    sourceReference: "日语学习",
    translations: [
      {
        id: "2",
        targetLanguage: "zh-CN",
        translatedText: "今天天气很好呢。",
        translationType: "native",
        isAutoGenerated: false
      }
    ],
    focusedWords: [
      {
        id: "2",
        wordText: "今日",
        startPosition: 0,
        endPosition: 2,
        pronunciation: "きょう"
      },
      {
        id: "3",
        wordText: "天気",
        startPosition: 3,
        endPosition: 5,
        pronunciation: "てんき"
      }
    ],
    wordPhrases: []
  },
  {
    originalText: "Bonjour, comment allez-vous?",
    languageCode: "fr-FR",
    sourceType: "manual",
    sourceReference: "法语基础",
    translations: [
      {
        id: "3",
        targetLanguage: "zh-CN",
        translatedText: "你好，您怎么样？",
        translationType: "native",
        isAutoGenerated: false
      },
      {
        id: "4",
        targetLanguage: "en-US",
        translatedText: "Hello, how are you?",
        translationType: "target",
        isAutoGenerated: false
      }
    ],
    focusedWords: [
      {
        id: "4",
        wordText: "Bonjour",
        startPosition: 0,
        endPosition: 7,
        pronunciation: ""
      }
    ],
    wordPhrases: []
  }
];

// 示例书籍数据
export const sampleBooks: Omit<Book, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: "英语学习指南",
    author: "张三",
    languageCode: "zh-CN",
    fileType: "pdf",
    totalPages: 200,
    currentPage: 45,
    readingProgress: 22.5,
    totalReadingTime: 180,
    lastReadAt: new Date(),
    chapters: [
      {
        id: "1",
        bookId: "book1",
        chapterTitle: "第一章 基础语法",
        chapterOrder: 1,
        startPage: 1,
        endPage: 50,
        createdAt: new Date()
      },
      {
        id: "2",
        bookId: "book1",
        chapterTitle: "第二章 词汇学习",
        chapterOrder: 2,
        startPage: 51,
        endPage: 100,
        createdAt: new Date()
      }
    ],
    summaries: [
      {
        id: "1",
        bookId: "book1",
        chapterId: "1",
        summaryType: "chapter",
        summaryText: "本章介绍了英语的基础语法知识，包括时态、语态和句型结构。",
        summaryOrder: 1,
        startPosition: 0,
        endPosition: 1000,
        createdAt: new Date()
      }
    ],
    notes: [
      {
        id: "1",
        bookId: "book1",
        noteType: "highlight",
        noteText: "重要的语法点",
        startPosition: 100,
        endPosition: 200,
        pageNumber: 10,
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ]
  },
  {
    title: "Japanese for Beginners",
    author: "田中太郎",
    languageCode: "ja-JP",
    fileType: "epub",
    totalPages: 150,
    currentPage: 30,
    readingProgress: 20.0,
    totalReadingTime: 120,
    lastReadAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2天前
    chapters: [
      {
        id: "3",
        bookId: "book2",
        chapterTitle: "第1章 ひらがなとカタカナ",
        chapterOrder: 1,
        startPage: 1,
        endPage: 30,
        createdAt: new Date()
      }
    ],
    summaries: [],
    notes: []
  }
];

// 示例学习记录
export const sampleLearningRecords = [
  {
    id: "1",
    sentenceId: "sentence1",
    learningType: "sentence_translation" as const,
    familiarityLevel: "familiar" as const,
    reviewCount: 3,
    lastReviewedAt: new Date(),
    nextReviewAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // 3天后
    easeFactor: 2.3,
    intervalDays: 3
  },
  {
    id: "2",
    sentenceId: "sentence2",
    learningType: "sentence_translation" as const,
    familiarityLevel: "mastered" as const,
    reviewCount: 5,
    lastReviewedAt: new Date(),
    nextReviewAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7天后
    easeFactor: 2.8,
    intervalDays: 7
  }
];

// 语言学习统计示例
export const sampleLearningStats = {
  total: 50,
  mastered: 15,
  familiar: 20,
  unfamiliar: 10,
  unlearned: 5,
  averageEaseFactor: 2.4,
  averageInterval: 4.2,
  nextReviewCount: 8
};

// 学习建议示例
export const sampleLearningAdvice = [
  "建议增加学习频率，每天至少复习20-30个句子",
  "重点关注不熟悉的句子，多进行翻译练习",
  "有较多句子需要复习，建议优先处理",
  "整体难度较高，建议放慢学习节奏"
];

// 初始化示例数据
export const initializeSampleData = () => {
  // 这里可以用于初始化示例数据到store中
  console.log('Sample data initialized');
  return {
    sentences: sampleSentences,
    books: sampleBooks,
    learningRecords: sampleLearningRecords,
    stats: sampleLearningStats,
    advice: sampleLearningAdvice
  };
};
